"""delete_active_status_from_user_table

Revision ID: 311971d97027
Revises: 4fe12c215735
Create Date: 2026-04-27 22:52:47.409613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '311971d97027'
down_revision: Union[str, Sequence[str], None] = '4fe12c215735'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'disabled')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('disabled', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
