"""init

Revision ID: 04567ab8349d
Revises:
Create Date: 2026-02-26 20:27:36.025619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '04567ab8349d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.PrimaryKeyConstraint('title')
    )
    op.create_table('mods',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('modcategories',
    sa.Column('mod_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.title'], ),
    sa.ForeignKeyConstraint(['mod_id'], ['mods.id'], ),
    sa.PrimaryKeyConstraint('mod_id', 'category_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('modcategories')
    op.drop_table('mods')
    op.drop_table('categories')
    # ### end Alembic commands ###
