"""delete_versions_and_categories2

Revision ID: 0e62f13dc597
Revises: 8ff0f3e254f1
Create Date: 2026-03-03 22:12:51.552630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0e62f13dc597'
down_revision: Union[str, Sequence[str], None] = '8ff0f3e254f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories')
    op.drop_table('modversions')
    op.drop_table('versions')
    op.drop_table('modcategories')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modcategories',
    sa.Column('mod_id', sa.CHAR(length=32), nullable=False),
    sa.Column('category_id', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.title'], ),
    sa.ForeignKeyConstraint(['mod_id'], ['mods.id'], ),
    sa.PrimaryKeyConstraint('mod_id', 'category_id')
    )
    op.create_table('versions',
    sa.Column('version', sa.VARCHAR(length=10), nullable=False),
    sa.PrimaryKeyConstraint('version')
    )
    op.create_table('modversions',
    sa.Column('mod_id', sa.CHAR(length=32), nullable=False),
    sa.Column('version_id', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['mod_id'], ['mods.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['versions.version'], ),
    sa.PrimaryKeyConstraint('mod_id', 'version_id')
    )
    op.create_table('categories',
    sa.Column('title', sa.VARCHAR(length=32), nullable=False),
    sa.PrimaryKeyConstraint('title')
    )
    # ### end Alembic commands ###
