"""add table versions

Revision ID: 8ff0f3e254f1
Revises: 04567ab8349d
Create Date: 2026-02-26 21:04:04.669390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8ff0f3e254f1'
down_revision: Union[str, Sequence[str], None] = '04567ab8349d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('versions',
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.PrimaryKeyConstraint('version')
    )
    op.create_table('modversions',
    sa.Column('mod_id', sa.Uuid(), nullable=False),
    sa.Column('version_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['mod_id'], ['mods.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['versions.version'], ),
    sa.PrimaryKeyConstraint('mod_id', 'version_id')
    )
    # SQLite doesn't support ALTER COLUMN TYPE; use batch mode (table rebuild).
    with op.batch_alter_table('categories') as batch_op:
        batch_op.alter_column(
            'title',
            existing_type=sa.VARCHAR(length=10),
            type_=sqlmodel.sql.sqltypes.AutoString(length=32),
            existing_nullable=False,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories') as batch_op:
        batch_op.alter_column(
            'title',
            existing_type=sqlmodel.sql.sqltypes.AutoString(length=32),
            type_=sa.VARCHAR(length=10),
            existing_nullable=False,
        )
    op.drop_table('modversions')
    op.drop_table('versions')
    # ### end Alembic commands ###
