"""1

Revision ID: bdc4eb724f91
Revises: 
Create Date: 2026-04-04 17:48:34.927816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bdc4eb724f91'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_versions_version'), 'versions', ['version'], unique=True)
    op.create_table('mod_version_links',
    sa.Column('mod_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mod_id'], ['mods.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['versions.id'], ),
    sa.PrimaryKeyConstraint('mod_id', 'version_id')
    )
    op.drop_table('mod_category_links')
    op.drop_table('mod_minecraft_version_links')
    op.drop_index(op.f('ix_minecraft_versions_version'), table_name='minecraft_versions')
    op.drop_table('minecraft_versions')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_mods_name'), table_name='mods')
    op.create_unique_constraint(None, 'mods', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mods', type_='unique')
    op.create_index(op.f('ix_mods_name'), 'mods', ['name'], unique=True)
    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('categories_pkey'))
    )
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_table('minecraft_versions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('version', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('minecraft_versions_pkey'))
    )
    op.create_index(op.f('ix_minecraft_versions_version'), 'minecraft_versions', ['version'], unique=True)
    op.create_table('mod_minecraft_version_links',
    sa.Column('mod_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('minecraft_version_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['minecraft_version_id'], ['minecraft_versions.id'], name=op.f('mod_minecraft_version_links_minecraft_version_id_fkey')),
    sa.ForeignKeyConstraint(['mod_id'], ['mods.id'], name=op.f('mod_minecraft_version_links_mod_id_fkey')),
    sa.PrimaryKeyConstraint('mod_id', 'minecraft_version_id', name=op.f('mod_minecraft_version_links_pkey'))
    )
    op.create_table('mod_category_links',
    sa.Column('mod_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('mod_category_links_category_id_fkey')),
    sa.ForeignKeyConstraint(['mod_id'], ['mods.id'], name=op.f('mod_category_links_mod_id_fkey')),
    sa.PrimaryKeyConstraint('mod_id', 'category_id', name=op.f('mod_category_links_pkey'))
    )
    op.drop_table('mod_version_links')
    op.drop_index(op.f('ix_versions_version'), table_name='versions')
    op.drop_table('versions')
    # ### end Alembic commands ###
